### PR TITLE
[WIP] Query param matcher API

### PR DESCRIPTION
**Pull request by lstrojny**
Should allow to check for the existence of query params. Q: should there be an API to do a full match?

### CODE REVIEW

**Comment by michaelherold** [comment]
I know that a "partial match" would be handy because it could cut down on some typing. But the basic grammar is enough to start using it.

**Comment by lstrojny** [comment]
Can you elaborate?

**Comment by michaelherold** [comment]
I'm primarily a Ruby developer. In RSpec, one of the Ruby testing frameworks, you can "partially match" a hash (in PHP, an associative array) with something like this:

```ruby
require "rspec/autorun"

class Demo
  def initialize(arg)
    @arg = arg
  end
end

RSpec.describe "hash_including" do
  it "partially matches hashes" do
    hash = {:key => "value", :key2 => "value2"}

    expect(Demo).to receive(:new).with hash_including(:key => "value")

    Demo.new(hash)
  end
end
```

This spec checks to make sure that `Demo.new` is called with a hash including the key `:key` and the value `"value"`. If it's called with any hash with that key/value combination, the spec will pass.

I was picturing something similar for checking query parameters in this context. Something like:

```php
$this->http->mock
    ->when()
        ->methodIs("GET")
        ->pathIs("/my/test/path")
        ->queryContains(array("param1" => "test1", "param2" => "test2"))
    ->then()->body("{}")->statusCode(200)
    ->end();
```

So you could call to `/my/test/path?param1=test1&param2=test2&param3=test3` and it would still respond with this mock.

I see this being useful when you're making a client that always sets a particular parameter like `access_token=mybearertoken`. However, this is really just sugar on what you already have, since this can be expressed equivalently with:

```php
$this->http->mock
    ->when()
        ->methodIs("GET")
        ->pathIs("/my/test/path")
        ->queryParamIs("param1", "test1")
        ->queryParamIs("param2", "test2")
    ->then()->body("{}")->statusCode(200)
    ->end();
```

Does that make sense?

**Comment by lstrojny** [comment]
Understood. So we could add a {{queryParamsAre(array …)}} and {{queryParamseExist(array …)}} methods.

**Comment by michaelherold** [comment]
This looks fantastic! Thanks for taking the time to add it. :+1:

**Pull request merged**
