### PR TITLE
Fix: PHP 7.4 cli logs in stderr

### PR DESCRIPTION
**Pull request by gabfr**
This fixes the issue #53 and aims to continue the PR #50.

Thanks @mtils and @lstrojny for the help in investigating and proposing a solution!

### CODE REVIEW

**Comment by lstrojny** [comment]
Thank you!

**Comment by TZK-** [comment]
Can you push a new release so we can update the package with composer easily and not to have to update like that `composer require internations/http-mock:dev-master#b2b4f2774d34733c3b9bebcbac1e76a34898bdcc` ?

Would be very great :smile:

**Comment by lstrojny** [comment]
Sure, done, 0.13.0 is out

**Comment by TZK-** [comment]
Thank you !

PS: The package is not auto updated on packagist, I triggered the refresh manually;
It would be great to use their webhook for the futur updates ;)

**Pull request merged**
