### PR TITLE
Updated silex/silex dependency to ~2.0

### PR DESCRIPTION
**Pull request by costinh**
Updated silex/silex dependency to ~2.0

### CODE REVIEW

**Comment by costinh** [comment]
Tests fail with en error that I've fixed in here https://github.com/InterNations/TestingComponent/pull/3

**Comment by lstrojny** [comment]
Thanks for the contribution. Can you rollback the code style changes and just have the request stack change in it?

**Comment by costinh** [comment]
Sure, done

**Comment by lstrojny** [comment]
Thank you!

**Pull request merged**
